### PR TITLE
Add Tajik (tg) to product-details

### PR DESCRIPTION
**Pull request by flodolo**
* English name: Tajik
* Native name: Тоҷикӣ

### CODE REVIEW

**Comment by jmaher** [comment]
I don't know what is required here, but at the very least do we need to update `public/1.0/regions/index.html` ?

**Comment by flodolo** [comment]
I've never touched anything outside of the languages file (see previous PRs). 

I have to manually updating this repository because otherwise mozilla.org won't show the build on the download page
https://www.mozilla.org/en-US/firefox/nightly/all/

**Comment by MihaiTabara** [comment]
Judging by https://github.com/mozilla-releng/product-details/pull/5/files and https://github.com/mozilla-releng/product-details/pull/4/files this seems to be fine. Not sure if we need to, but we can probably force Product-Details from Ship-it in order for it to get rebuild + deployed.

**Comment by flodolo** [comment]
It's really not urgent, so I typically wait for the next "natural" push (normally the next beta).

**Review by jmaher — APPROVED** [review]
thanks, LGTM

**Pull request merged**
